# Generated by Django 2.1.3 on 2018-11-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_seqprocess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seqprocess',
            name='accountcurrency',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seqprocess',
            name='accountname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seqprocess',
            name='accountno',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seqprocess',
            name='appropriatype',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seqprocess',
            name='bankid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seqprocess',
            name='branchname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seqprocess',
            name='investadvaddr',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
